Remove upstream's autoupdate mechanism
rbrito/pkg-youtube-dl pull request #2
Opened 2018-02-11 11:05 UTC by nbraud

The autoupdate function is defunct on Debian anyway, and the signature validation code is fairly sketchy.

Closes: [#890119](https://bugs.debian.org/890119)

2018-02-18 23:24 UTC, rbrito requested changes
These are the comments that I posted to the Debian BTS:

-----

I am OK (not super happy, but OK) with the removal of the --upgrade option of youtube-dl, *BUT* I think that removing it completely and giving the users that try to invoke the command with that option something like "option not recognized" is a poor user-experience.

We should, *IF* we remove the option, substitute it with an output saying that in Debian (and other derived distributions) we have disabled that option.  Not having this will make users confused, since it would deviate
from the behavior of upstream.

Speaking as a user (not as the maintainer) of youtube-dl, that's something that I would expect from *any* Debian package: document conspicuously the differences between the package that we have in Debian and what upstream offers.

-----

Can you add an explanation of why the upstream code is poorly designed? Even then, I think that the program would need a stub option to let the users know what is different between the Debian and the upstream versions.

2018-02-24 16:08 UTC, nbraud commented
@rbrito I updated the patch and made `youtube-dl` provide a more helpful error message.

2018-02-24 19:01 UTC, GLolol commented
Just to make the patch more future proof, I wonder if it'd be a better idea to just leave the update code as dead code instead of removing it entirely. This would reduce the patch to only changing two blocks AFAICT.

2018-03-16 16:46 UTC, rbrito commented
I will merge this and make the changes suggested by @GLolol, since they will be easier for maintenance in the long run.

Thanks a lot!

2018-03-16 16:49 UTC, merged